auto: true
permalink: /:year/:month/:day/:title
pygments: true
paginate: 5
exclude:
- README.md
- Rakefile
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
